[profile.default]
solc_version = "0.8.26"
evm_version = "cancun"
ffi = true
fs_permissions = [{ access = "read-write", path = ".forge-snapshots/"}]

optimizer = true
optimizer_runs = 9_999_999

remappings = [
  "@v4=lib/v4-core/",
  "@solady=lib/solady/",
  "@forge=lib/forge-std/src/",
  "@uniswap/v4-core/=lib/v4-core/"
]

[fmt]
line_length = 100

[rpc_endpoints]
main = "https://rpc.ankr.com/eth"
base = "https://rpc.ankr.com/base"
poly = "https://rpc.ankr.com/polygon"
opti = "https://rpc.ankr.com/optimism"
arbi = "https://rpc.ankr.com/arbitrum"