[profile.default]
solc_version = "0.8.30"
evm_version = "cancun"
ffi = true
fs_permissions = [{ access = "read-write", path = ".forge-snapshots/"}]

via_ir = true
optimizer = true
optimizer_runs = 9_999_999

additional_compiler_profiles = [
  { name = "test", via_ir = true, optimizer_runs = 1 }
]

compilation_restrictions = [
  { paths = "test/**", via_ir = true, optimizer_runs = 1 }
]

remappings = [
  "@v4=lib/v4-core/",
  "@solady=lib/solady/",
  "v4-core/=lib/v4-core/",
  "@permit2=lib/permit2/src/",
  "@forge=lib/forge-std/src/",
  "@uniswap/v4-core/=lib/v4-core/",
  "@v4-periphery/=lib/v4-periphery/",
  "forge-std/=lib/v4-core/lib/forge-std/src/",
  "@universal-router/=lib/universal-router/contracts/",
  "@hookmate/=lib/hookmate/src/"
]

[fmt]
line_length = 100

[rpc_endpoints]
main = "https://rpc.ankr.com/eth"
base = "https://rpc.ankr.com/base"
poly = "https://rpc.ankr.com/polygon"
opti = "https://rpc.ankr.com/optimism"
arbi = "https://rpc.ankr.com/arbitrum"